//! Session persistence: save and restore chat histories.
//!
//! Sessions are stored as JSON files under the platform data directory:
//! - Windows: `%APPDATA%/filar/sessions/<id>.json`
//! - macOS:   `~/Library/Application Support/filar/sessions/<id>.json`
//! - Linux:   `$XDG_DATA_HOME/filar/sessions/` or `~/.local/share/filar/sessions/`
//!
//! At most [`MAX_SESSIONS`] sessions are kept; older ones are pruned.

use std::collections::HashMap;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use crate::chat::ChatBlock;
use crate::config::CommandConfirmMode;
use crate::error::{CoreError, Result};

/// Maximum number of sessions to retain on disk.
pub const MAX_SESSIONS: usize = 10;

/// Maximum number of input history entries to persist per session.
pub const MAX_INPUT_HISTORY: usize = 200;

// ---------------------------------------------------------------------------
// ProfileUsage
// ---------------------------------------------------------------------------

/// Per-profile token consumption accumulated during a session.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ProfileUsage {
    /// Cumulative input tokens consumed by this profile.
    #[serde(default)]
    pub tokens_in: u64,
    /// Cumulative output tokens generated by this profile.
    #[serde(default)]
    pub tokens_out: u64,
}

// ---------------------------------------------------------------------------
// Session
// ---------------------------------------------------------------------------

/// A saved chat session.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Session {
    /// Unique identifier (Unix timestamp as a string).
    pub id: String,
    /// Human-readable timestamp (ISO-ish: `YYYY-MM-DD HH:MM:SS`).
    pub timestamp: String,
    /// Target name that was connected to.
    pub target: String,
    /// LLM profile name that was used.
    #[serde(default)]
    pub llm_profile: Option<String>,
    /// Chat history blocks.
    pub messages: Vec<ChatBlock>,
    /// History of user prompts in agent mode (for Up/Down navigation).
    /// Limited to [`MAX_INPUT_HISTORY`] entries when saved.
    #[serde(default)]
    pub input_history: Vec<String>,
    /// Cumulative input tokens (from API usage data).
    #[serde(default)]
    pub tokens_in: u64,
    /// Cumulative output tokens (from API usage data).
    #[serde(default)]
    pub tokens_out: u64,
    /// Cumulative cost in USD (from `usage.cost`). Summed across all profiles.
    #[serde(default)]
    pub cost_usd: Option<f64>,
    /// Per-profile token consumption breakdown.
    #[serde(default)]
    pub per_profile: HashMap<String, ProfileUsage>,
    /// The last actually served model slug reported by the provider.
    #[serde(default)]
    pub last_served_model: Option<String>,
    /// Actually served model slug per profile (overrides `last_served_model`).
    /// Keyed by profile name. `#[serde(default)]` for backward compat.
    #[serde(default)]
    pub model_per_profile: HashMap<String, String>,
    /// SSH connection info the session was launched with (e.g. `user@host:port`).
    /// `None` = local. `#[serde(default)]` for backward compat.
    #[serde(default)]
    pub ssh_info: Option<String>,
    /// Model identifier used at launch (e.g. `glm-5.1`). `#[serde(default)]`.
    #[serde(default)]
    pub model: Option<String>,
    /// API base URL used at launch. `#[serde(default)]`.
    #[serde(default)]
    pub api_base_url: Option<String>,
    /// Command confirmation mode at launch. `#[serde(default)]`.
    #[serde(default)]
    pub confirm_mode: Option<CommandConfirmMode>,
}

/// Lightweight metadata for listing sessions without loading full messages.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionMeta {
    pub id: String,
    pub timestamp: String,
    pub target: String,
    pub llm_profile: Option<String>,
    /// SSH connection info (e.g. `user@host:port`). `None` = local.
    #[serde(default)]
    pub ssh_info: Option<String>,
    /// Model identifier used at launch.
    #[serde(default)]
    pub model: Option<String>,
    /// API base URL used at launch.
    #[serde(default)]
    pub api_base_url: Option<String>,
    /// Preview of the first user message (or system message).
    pub preview: String,
}

impl From<&Session> for SessionMeta {
    fn from(s: &Session) -> Self {
        let preview = s
            .messages
            .iter()
            .find(|b| matches!(b, ChatBlock::User(_)))
            .or_else(|| s.messages.first())
            .map(|b| b.preview())
            .unwrap_or_default();
        Self {
            id: s.id.clone(),
            timestamp: s.timestamp.clone(),
            target: s.target.clone(),
            llm_profile: s.llm_profile.clone(),
            ssh_info: s.ssh_info.clone(),
            model: s.model.clone(),
            api_base_url: s.api_base_url.clone(),
            preview,
        }
    }
}

// ---------------------------------------------------------------------------
// Session methods
// ---------------------------------------------------------------------------

impl Session {
    /// Truncate `input_history` to at most [`MAX_INPUT_HISTORY`] entries,
    /// keeping the most recent.
    pub fn truncate_history(&mut self) {
        let max = MAX_INPUT_HISTORY;
        if self.input_history.len() > max {
            let excess = self.input_history.len() - max;
            self.input_history.drain(0..excess);
        }
    }
}

// ---------------------------------------------------------------------------
// SessionStore
// ---------------------------------------------------------------------------

/// Manages session files on disk.
pub struct SessionStore {
    dir: PathBuf,
}

impl SessionStore {
    /// Returns the sessions directory path.
    pub fn dir(&self) -> &std::path::Path {
        &self.dir
    }

    /// Create a store with a specific base directory.
    ///
    /// The sessions directory will be `base_dir/filar/sessions`.
    /// This allows external consumers (bots, mobile apps) to specify a
    /// platform-appropriate path without relying on `APPDATA` or `HOME`.
    pub fn new(base_dir: PathBuf) -> Result<Self> {
        let dir = base_dir.join("filar").join("sessions");
        std::fs::create_dir_all(&dir)?;
        Ok(Self { dir })
    }

    /// Create a store using the platform-default base directory.
    ///
    /// See [`default_base_dir`]. For cross-compilation targets (Android, iOS)
    /// where an OS data dir is unavailable, use [`new`](Self::new) with an
    /// explicit path.
    pub fn with_default_dir() -> Result<Self> {
        Self::new(default_base_dir()?)
    }

    /// Save a session to disk atomically (overwrites if the ID already exists).
    ///
    /// The JSON is written to a temporary file first and then renamed over the
    /// target, so a crash mid-write never leaves a truncated or corrupt session
    /// file — the previous (complete) version stays in place until the rename.
    pub fn save(&self, session: &Session) -> Result<()> {
        let path = self.dir.join(format!("{}.json", session.id));
        let tmp = self
            .dir
            .join(format!("{}.json.tmp{}", session.id, std::process::id()));
        let json = serde_json::to_string_pretty(session)
            .map_err(|e| CoreError::Other(format!("failed to serialise session: {e}")))?;
        std::fs::write(&tmp, json)?;
        if let Err(e) = std::fs::rename(&tmp, &path) {
            let _ = std::fs::remove_file(&tmp);
            return Err(CoreError::Other(format!(
                "failed to replace session file {}: {e}",
                path.display()
            )));
        }
        tracing::info!(session_id = %session.id, path = %path.display(), "session saved");
        Ok(())
    }

    /// Load a session by ID. Returns `None` if the file does not exist.
    pub fn load(&self, id: &str) -> Result<Option<Session>> {
        let path = self.dir.join(format!("{id}.json"));
        if !path.exists() {
            return Ok(None);
        }
        let contents = std::fs::read_to_string(&path)?;
        let session: Session = serde_json::from_str(&contents)
            .map_err(|e| CoreError::Other(format!("failed to parse session {id}: {e}")))?;
        Ok(Some(session))
    }

    /// List metadata for all stored sessions, sorted newest-first.
    pub fn list(&self) -> Result<Vec<SessionMeta>> {
        let mut metas = Vec::new();
        if !self.dir.exists() {
            return Ok(metas);
        }
        for entry in std::fs::read_dir(&self.dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("json") {
                continue;
            }
            match std::fs::read_to_string(&path) {
                Ok(contents) => {
                    match serde_json::from_str::<Session>(&contents) {
                        Ok(session) => metas.push(SessionMeta::from(&session)),
                        Err(e) => {
                            tracing::warn!(path = %path.display(), error = %e, "skipping unparseable session file");
                        }
                    }
                }
                Err(e) => {
                    tracing::warn!(path = %path.display(), error = %e, "skipping unreadable session file");
                }
            }
        }
        // Sort newest-first (IDs are timestamps, so string sort works).
        metas.sort_by(|a, b| b.id.cmp(&a.id));
        Ok(metas)
    }

    /// Delete sessions beyond `max`, keeping the newest.
    pub fn prune_to(&self, max: usize) -> Result<()> {
        let metas = self.list()?;
        if metas.len() <= max {
            return Ok(());
        }
        // metas is sorted newest-first; delete everything after index `max`.
        for meta in metas.into_iter().skip(max) {
            let path = self.dir.join(format!("{}.json", meta.id));
            tracing::info!(session_id = %meta.id, "pruning old session");
            let _ = std::fs::remove_file(&path);
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Determine the platform-default **parent** directory for filar data.
///
/// Returns the OS user data directory (`dirs::data_dir`):
/// - Windows → `%APPDATA%` (Roaming)
/// - macOS → `~/Library/Application Support`
/// - Linux → `$XDG_DATA_HOME` or `~/.local/share`
///
/// App files live under `{base}/filar/` (`settings.json`, `pending_launch.json`,
/// `config.toml`, `sessions/`, `logs/`). This function does **not** create
/// directories — use it when you only need the base path. For session storage,
/// use [`SessionStore::with_default_dir`].
///
/// On Unix, if a legacy `$HOME/filar` directory exists and the new
/// `{data_dir}/filar` does not, it is renamed once (best-effort; failures are
/// logged and ignored so startup still proceeds).
pub fn default_base_dir() -> Result<PathBuf> {
    let base = dirs::data_dir().ok_or_else(|| {
        CoreError::Other(
            "could not determine OS data directory (dirs::data_dir returned None)".into(),
        )
    })?;

    #[cfg(unix)]
    try_migrate_legacy_home_filar(&base);

    Ok(base)
}

/// Best-effort one-shot migration from legacy `$HOME/filar` to
/// `{data_dir}/filar` (macOS Application Support / Linux XDG).
///
/// No-op when the legacy path is missing, the destination already exists, or
/// `HOME` is unset. Exposed for unit tests.
#[cfg(any(unix, test))]
pub(crate) fn migrate_legacy_filar_dir(
    legacy_filar: &std::path::Path,
    new_filar: &std::path::Path,
) -> std::io::Result<bool> {
    if !legacy_filar.is_dir() || new_filar.exists() {
        return Ok(false);
    }
    if let Some(parent) = new_filar.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::rename(legacy_filar, new_filar)?;
    Ok(true)
}

#[cfg(unix)]
fn try_migrate_legacy_home_filar(data_dir: &std::path::Path) {
    let Some(home) = std::env::var_os("HOME").map(PathBuf::from) else {
        return;
    };
    let legacy = home.join("filar");
    let dest = data_dir.join("filar");
    // Skip when legacy path is already the destination (e.g. unusual HOME).
    if legacy == dest {
        return;
    }
    match migrate_legacy_filar_dir(&legacy, &dest) {
        Ok(true) => {
            tracing::info!(
                from = %legacy.display(),
                to = %dest.display(),
                "migrated legacy filar data directory"
            );
        }
        Ok(false) => {}
        Err(e) => {
            tracing::warn!(
                from = %legacy.display(),
                to = %dest.display(),
                error = %e,
                "failed to migrate legacy filar data directory; continuing with new path"
            );
        }
    }
}

/// Generate a session ID and human-readable timestamp from the current time.
pub fn now_session_id() -> (String, String) {
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();

    // Simple UTC timestamp formatting without external deps.
    let (year, month, day, hour, min, sec) = unix_to_ymdhms(secs);
    let id = format!("{secs}");
    let timestamp = format!("{year:04}-{month:02}-{day:02} {hour:02}:{min:02}:{sec:02}");
    (id, timestamp)
}

/// Convert a Unix timestamp (seconds) to broken-down UTC time.
///
/// This is a minimal implementation that avoids pulling in `chrono`.
fn unix_to_ymdhms(secs: u64) -> (u32, u32, u32, u32, u32, u32) {
    let days = (secs / 86_400) as i64;
    let rem = secs % 86_400;
    let hour = (rem / 3600) as u32;
    let min = ((rem % 3600) / 60) as u32;
    let sec = (rem % 60) as u32;

    // Days since 1970-01-01 → calendar date (Howard Hinnant's algorithm).
    let z = days + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = (z - era * 146_097) as u64;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe as i64 + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32;
    let m = if mp < 10 { mp + 3 } else { mp - 9 } as u32;
    let year = if m <= 2 { y + 1 } else { y } as u32;

    (year, m, d, hour, min, sec)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn session_meta_from_session() {
        let session = Session {
            id: "123".into(),
            timestamp: "2026-06-21 12:00:00".into(),
            target: "local".into(),
            llm_profile: Some("default".into()),
            messages: vec![
                ChatBlock::System("connected".into()),
                ChatBlock::User("find port 8080".into()),
                ChatBlock::Agent("running lsof".into()),
            ],
            input_history: vec![],
            tokens_in: 0,
            tokens_out: 0,
            cost_usd: None,
            per_profile: HashMap::new(),
            last_served_model: None,
            model_per_profile: HashMap::new(),
            ssh_info: None,
            model: None,
            api_base_url: None,
            confirm_mode: None,
        };
        let meta = SessionMeta::from(&session);
        assert_eq!(meta.id, "123");
        assert_eq!(meta.target, "local");
        assert_eq!(meta.preview, "You: find port 8080");
    }

    #[test]
    fn session_meta_empty_messages() {
        let session = Session {
            id: "1".into(),
            timestamp: "t".into(),
            target: "t".into(),
            llm_profile: Some("t".into()),
            messages: vec![],
            input_history: vec![],
            tokens_in: 0,
            tokens_out: 0,
            cost_usd: None,
            per_profile: HashMap::new(),
            last_served_model: None,
            model_per_profile: HashMap::new(),
            ssh_info: None,
            model: None,
            api_base_url: None,
            confirm_mode: None,
        };
        let meta = SessionMeta::from(&session);
        assert!(meta.preview.is_empty());
    }

    #[test]
    fn session_store_save_is_atomic() {
        let tmp = std::env::temp_dir().join(format!("filar_atomic_{}", std::process::id()));
        std::fs::create_dir_all(&tmp).unwrap();

        let store = SessionStore { dir: tmp.clone() };
        let session = Session {
            id: "777".into(),
            timestamp: "2026-01-01 00:00:00".into(),
            target: "test".into(),
            llm_profile: Some("glm".into()),
            messages: vec![ChatBlock::User("hello".into())],
            input_history: vec![],
            tokens_in: 0,
            tokens_out: 0,
            cost_usd: None,
            per_profile: HashMap::new(),
            last_served_model: None,
            model_per_profile: HashMap::new(),
            ssh_info: None,
            model: None,
            api_base_url: None,
            confirm_mode: None,
        };

        store.save(&session).unwrap();

        // The temp file must be renamed away and only the final file remain.
        assert!(tmp.join("777.json").exists());
        let leftovers: Vec<_> = std::fs::read_dir(&tmp)
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .filter(|n| n.contains(".tmp"))
            .collect();
        assert!(leftovers.is_empty(), "no temp files should remain: {leftovers:?}");

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn session_store_save_load_roundtrip() {
        // Use a temp directory for testing.
        let tmp = std::env::temp_dir().join(format!("filar_test_{}", std::process::id()));
        std::fs::create_dir_all(&tmp).unwrap();

        let store = SessionStore {
            dir: tmp.clone(),
        };

        let session = Session {
            id: "999".into(),
            timestamp: "2026-01-01 00:00:00".into(),
            target: "test".into(),
            llm_profile: Some("glm".into()),
            messages: vec![
                ChatBlock::User("hello".into()),
                ChatBlock::Agent("world".into()),
            ],
            input_history: vec!["ls -la".into(), "find port".into()],
            tokens_in: 0,
            tokens_out: 0,
            cost_usd: None,
            per_profile: HashMap::new(),
            last_served_model: None,
            model_per_profile: HashMap::new(),
            ssh_info: None,
            model: None,
            api_base_url: None,
            confirm_mode: None,
        };

        store.save(&session).unwrap();
        let loaded = store.load("999").unwrap().unwrap();
        assert_eq!(loaded.id, "999");
        assert_eq!(loaded.target, "test");
        assert_eq!(loaded.messages.len(), 2);
        assert_eq!(loaded.input_history, session.input_history);

        let metas = store.list().unwrap();
        assert_eq!(metas.len(), 1);
        assert_eq!(metas[0].preview, "You: hello");

        // Loading non-existent session.
        assert!(store.load("nonexistent").unwrap().is_none());

        // Clean up.
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn session_store_prune() {
        let tmp = std::env::temp_dir().join(format!("filar_prune_{}", std::process::id()));
        std::fs::create_dir_all(&tmp).unwrap();

        let store = SessionStore {
            dir: tmp.clone(),
        };

        // Save 5 sessions with different IDs (timestamps).
        for i in 1..=5u64 {
            let session = Session {
                id: format!("{i:010}"),
                timestamp: format!("t{i}"),
                target: "t".into(),
                llm_profile: Some("t".into()),
                messages: vec![ChatBlock::User(format!("msg{i}"))],
                input_history: vec![],
            tokens_in: 0,
            tokens_out: 0,
            cost_usd: None,
            per_profile: HashMap::new(),
            last_served_model: None,
            model_per_profile: HashMap::new(),
            ssh_info: None,
            model: None,
            api_base_url: None,
            confirm_mode: None,
            };
            store.save(&session).unwrap();
        }

        // Prune to 3.
        store.prune_to(3).unwrap();
        let metas = store.list().unwrap();
        assert_eq!(metas.len(), 3);
        // Newest 3 kept (IDs 0000000005, 0000000004, 0000000003).
        assert_eq!(metas[0].id, "0000000005");
        assert_eq!(metas[2].id, "0000000003");

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn session_store_new_creates_sessions_dir() {
        let tmp = std::env::temp_dir().join(format!(
            "filar_new_test_{}_{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos()
        ));
        // Ensure clean state.
        let _ = std::fs::remove_dir_all(&tmp);

        let store = SessionStore::new(tmp.clone()).unwrap();
        let expected = tmp.join("filar").join("sessions");
        assert!(expected.exists(), "sessions directory should be created");
        assert_eq!(store.dir(), expected);

        // Clean up.
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn session_store_with_default_dir_resolves_platform_path() {
        // with_default_dir() should succeed when the OS data dir is available,
        // and the resulting directory should be base/filar/sessions.
        let store = SessionStore::with_default_dir();
        if let Ok(s) = store {
            assert!(
                s.dir().ends_with(std::path::Path::new("filar/sessions")),
                "dir should end with filar/sessions, got: {}",
                s.dir().display()
            );
            assert!(s.dir().exists(), "directory should exist after creation");
        }
    }

    #[test]
    fn default_base_dir_does_not_create_directories() {
        if let Ok(base) = default_base_dir() {
            // The OS data dir itself should already exist.
            assert!(base.exists(), "base directory should already exist");
            // Must match dirs::data_dir() (Windows APPDATA / macOS Application Support / XDG).
            if let Some(expected) = dirs::data_dir() {
                assert_eq!(base, expected, "default_base_dir must use dirs::data_dir()");
            }
        }
    }

    #[test]
    fn migrate_legacy_filar_renames_when_dest_missing() {
        let tmp = std::env::temp_dir().join(format!("filar_migrate_test_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);
        let legacy = tmp.join("home").join("filar");
        let dest = tmp.join("data").join("filar");
        std::fs::create_dir_all(&legacy).unwrap();
        std::fs::write(legacy.join("settings.json"), "{}").unwrap();

        let migrated = migrate_legacy_filar_dir(&legacy, &dest).unwrap();
        assert!(migrated);
        assert!(!legacy.exists());
        assert!(dest.join("settings.json").exists());

        // Second call is a no-op.
        assert!(!migrate_legacy_filar_dir(&legacy, &dest).unwrap());

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn migrate_legacy_filar_skips_when_dest_exists() {
        let tmp = std::env::temp_dir().join(format!("filar_migrate_skip_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);
        let legacy = tmp.join("home").join("filar");
        let dest = tmp.join("data").join("filar");
        std::fs::create_dir_all(&legacy).unwrap();
        std::fs::create_dir_all(&dest).unwrap();
        std::fs::write(legacy.join("old.json"), "legacy").unwrap();
        std::fs::write(dest.join("new.json"), "fresh").unwrap();

        assert!(!migrate_legacy_filar_dir(&legacy, &dest).unwrap());
        assert!(legacy.join("old.json").exists());
        assert!(dest.join("new.json").exists());

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn unix_to_ymdhms_epoch() {
        let (y, m, d, h, mi, s) = unix_to_ymdhms(0);
        assert_eq!((y, m, d, h, mi, s), (1970, 1, 1, 0, 0, 0));
    }

    #[test]
    fn tokens_in_out_roundtrip() {
        let s = Session {
            id: "1".into(), timestamp: "t".into(), target: "t".into(),
            llm_profile: Some("glm".into()), messages: vec![], input_history: vec![],
            tokens_in: 150, tokens_out: 300,
            cost_usd: None, per_profile: HashMap::new(), last_served_model: None, model_per_profile: HashMap::new(),
            ssh_info: None, model: None, api_base_url: None, confirm_mode: None,
        };
        let json = serde_json::to_string(&s).unwrap();
        assert!(json.contains("tokens_in"), "must serialize tokens_in");
        assert!(json.contains("150"), "must serialize value");
        let loaded: Session = serde_json::from_str(&json).unwrap();
        assert_eq!(loaded.tokens_in, 150);
        assert_eq!(loaded.tokens_out, 300);
    }

    #[test]
    fn tokens_in_out_backward_compat() {
        let json = r#"{"id":"1","timestamp":"x","target":"x","llm_profile":"x","messages":[],"input_history":[]}"#;
        let loaded: Session = serde_json::from_str(json).unwrap();
        assert_eq!(loaded.tokens_in, 0, "missing field → default 0");
        assert_eq!(loaded.tokens_out, 0);
    }

    #[test]
    fn unix_to_ymdhms_known_date() {
        let (y, _m, _d, _h, _mi, _s) = unix_to_ymdhms(1_782_045_045);
        assert_eq!(y, 2026);
    }

    // ── input_history tests ────────────────────────────────────────────

    #[test]
    fn input_history_serialize_roundtrip() {
        let session = Session {
            id: "1".into(),
            timestamp: "t".into(),
            target: "t".into(),
            llm_profile: Some("t".into()),
            messages: vec![],
            input_history: vec!["ls".into(), "find port 8080".into()],
            tokens_in: 0,
            tokens_out: 0,
            cost_usd: None,
            per_profile: HashMap::new(),
            last_served_model: None,
            model_per_profile: HashMap::new(),
            ssh_info: None,
            model: None,
            api_base_url: None,
            confirm_mode: None,
        };
        let json = serde_json::to_string_pretty(&session).unwrap();
        assert!(json.contains("input_history"), "JSON must contain input_history");
        assert!(json.contains("find port 8080"), "must contain history entries");
        let loaded: Session = serde_json::from_str(&json).unwrap();
        assert_eq!(loaded.input_history.len(), 2);
        assert_eq!(loaded.input_history[0], "ls");
        assert_eq!(loaded.input_history[1], "find port 8080");
    }

    #[test]
    fn input_history_backward_compat_no_field() {
        // JSON from a session saved by the old version — no input_history field.
        let json = r#"{
            "id":"123",
            "timestamp":"2026-01-01 00:00:00",
            "target":"test",
            "llm_profile":"glm",
            "messages":[{"User":"hello"},{"Agent":"world"}]
        }"#;
        let session: Session = serde_json::from_str(json).unwrap();
        assert_eq!(session.id, "123");
        assert!(session.input_history.is_empty(), "missing field → default empty");
    }

    #[test]
    fn truncate_input_history_keeps_last_entries() {
        let mut session = Session {
            id: "1".into(),
            timestamp: "t".into(),
            target: "t".into(),
            llm_profile: Some("t".into()),
            messages: vec![],
            input_history: (0..250).map(|i| format!("entry{i}")).collect(),
            tokens_in: 0,
            tokens_out: 0,
            cost_usd: None,
            per_profile: HashMap::new(),
            last_served_model: None,
            model_per_profile: HashMap::new(),
            ssh_info: None,
            model: None,
            api_base_url: None,
            confirm_mode: None,
        };
        assert!(session.input_history.len() > MAX_INPUT_HISTORY);
        session.truncate_history();
        assert_eq!(session.input_history.len(), MAX_INPUT_HISTORY);
        assert_eq!(session.input_history[0], "entry50");
        assert_eq!(session.input_history.last().unwrap(), "entry249");
    }

    #[test]
    fn session_backward_compat_without_new_fields() {
        let old_json = r#"{
            "id":"1","timestamp":"t","target":"t",
            "messages":[],
            "input_history":[],
            "tokens_in":100,
            "tokens_out":200
        }"#;
        let s: Session = serde_json::from_str(old_json).unwrap();
        assert_eq!(s.tokens_in, 100);
        assert_eq!(s.tokens_out, 200);
        assert_eq!(s.cost_usd, None);
        assert!(s.per_profile.is_empty());
        assert_eq!(s.last_served_model, None);
    }

    #[test]
    fn model_per_profile_survives_roundtrip() {
        let mut session = Session {
            id: "1".into(), timestamp: "t".into(), target: "t".into(),
            llm_profile: None, messages: vec![], input_history: vec![],
            tokens_in: 0, tokens_out: 0,
            cost_usd: None, per_profile: HashMap::new(), last_served_model: None,
            model_per_profile: HashMap::new(),
            ssh_info: None,
            model: None,
            api_base_url: None,
            confirm_mode: None,
        };
        session.model_per_profile.insert("glm".into(), "openai/gpt-4o-mini".into());
        let json = serde_json::to_string(&session).unwrap();
        let restored: Session = serde_json::from_str(&json).unwrap();
        assert_eq!(restored.model_per_profile.get("glm").map(|s| s.as_str()), Some("openai/gpt-4o-mini"));
    }

    #[test]
    fn model_per_profile_is_empty_for_old_json() {
        let old_json = r#"{
            "id":"1","timestamp":"t","target":"t",
            "messages":[], "input_history":[],
            "tokens_in":0, "tokens_out":0
        }"#;
        let s: Session = serde_json::from_str(old_json).unwrap();
        assert!(s.model_per_profile.is_empty());
    }

    #[test]
    fn launch_context_roundtrip() {
        let session = Session {
            id: "1".into(),
            timestamp: "t".into(),
            target: "prod".into(),
            llm_profile: Some("glm".into()),
            messages: vec![],
            input_history: vec![],
            tokens_in: 0,
            tokens_out: 0,
            cost_usd: None,
            per_profile: HashMap::new(),
            last_served_model: None,
            model_per_profile: HashMap::new(),
            ssh_info: Some("root@10.0.0.5:22".into()),
            model: Some("glm-5.1".into()),
            api_base_url: Some("https://open.bigmodel.cn/api/paas/v4".into()),
            confirm_mode: Some(CommandConfirmMode::Always),
        };
        let json = serde_json::to_string(&session).unwrap();
        let restored: Session = serde_json::from_str(&json).unwrap();
        assert_eq!(restored.ssh_info.as_deref(), Some("root@10.0.0.5:22"));
        assert_eq!(restored.model.as_deref(), Some("glm-5.1"));
        assert_eq!(
            restored.api_base_url.as_deref(),
            Some("https://open.bigmodel.cn/api/paas/v4")
        );
        assert_eq!(restored.confirm_mode, Some(CommandConfirmMode::Always));
    }

    #[test]
    fn launch_context_backward_compat() {
        let old_json = r#"{
            "id":"1","timestamp":"t","target":"t",
            "messages":[], "input_history":[],
            "tokens_in":0, "tokens_out":0
        }"#;
        let s: Session = serde_json::from_str(old_json).unwrap();
        assert_eq!(s.ssh_info, None);
        assert_eq!(s.model, None);
        assert_eq!(s.api_base_url, None);
        assert_eq!(s.confirm_mode, None);
    }

    #[test]
    fn session_meta_includes_launch_context() {
        let session = Session {
            id: "1".into(),
            timestamp: "t".into(),
            target: "prod".into(),
            llm_profile: Some("glm".into()),
            messages: vec![ChatBlock::User("hi".into())],
            input_history: vec![],
            tokens_in: 0,
            tokens_out: 0,
            cost_usd: None,
            per_profile: HashMap::new(),
            last_served_model: None,
            model_per_profile: HashMap::new(),
            ssh_info: Some("root@10.0.0.5:22".into()),
            model: Some("glm-5.1".into()),
            api_base_url: Some("https://example.com".into()),
            confirm_mode: Some(CommandConfirmMode::Allowlist),
        };
        let meta = SessionMeta::from(&session);
        assert_eq!(meta.ssh_info.as_deref(), Some("root@10.0.0.5:22"));
        assert_eq!(meta.model.as_deref(), Some("glm-5.1"));
        assert_eq!(meta.api_base_url.as_deref(), Some("https://example.com"));
    }
}
