//! Session persistence: save and restore chat histories.
//!
//! Sessions are stored as JSON files in a per-user directory:
//! - Windows: `%APPDATA%/filar/sessions/<id>.json`
//! - Unix:    `$HOME/.filar/sessions/<id>.json`
//!
//! At most [`MAX_SESSIONS`] sessions are kept; older ones are pruned.

use std::collections::HashMap;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use crate::chat::ChatBlock;
use crate::error::{CoreError, Result};

/// Maximum number of sessions to retain on disk.
pub const MAX_SESSIONS: usize = 10;

/// Maximum number of input history entries to persist per session.
pub const MAX_INPUT_HISTORY: usize = 200;

// ---------------------------------------------------------------------------
// ProfileUsage
// ---------------------------------------------------------------------------

/// Per-profile token consumption accumulated during a session.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ProfileUsage {
    /// Cumulative input tokens consumed by this profile.
    #[serde(default)]
    pub tokens_in: u64,
    /// Cumulative output tokens generated by this profile.
    #[serde(default)]
    pub tokens_out: u64,
}

// ---------------------------------------------------------------------------
// Session
// ---------------------------------------------------------------------------

/// A saved chat session.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Session {
    /// Unique identifier (Unix timestamp as a string).
    pub id: String,
    /// Human-readable timestamp (ISO-ish: `YYYY-MM-DD HH:MM:SS`).
    pub timestamp: String,
    /// Target name that was connected to.
    pub target: String,
    /// LLM profile name that was used.
    #[serde(default)]
    pub llm_profile: Option<String>,
    /// Chat history blocks.
    pub messages: Vec<ChatBlock>,
    /// History of user prompts in agent mode (for Up/Down navigation).
    /// Limited to [`MAX_INPUT_HISTORY`] entries when saved.
    #[serde(default)]
    pub input_history: Vec<String>,
    /// Cumulative input tokens (from API usage data).
    #[serde(default)]
    pub tokens_in: u64,
    /// Cumulative output tokens (from API usage data).
    #[serde(default)]
    pub tokens_out: u64,
    /// Cumulative cost in USD (from `usage.cost`). Summed across all profiles.
    #[serde(default)]
    pub cost_usd: Option<f64>,
    /// Per-profile token consumption breakdown.
    #[serde(default)]
    pub per_profile: HashMap<String, ProfileUsage>,
    /// The last actually served model slug reported by the provider.
    #[serde(default)]
    pub last_served_model: Option<String>,
}

/// Lightweight metadata for listing sessions without loading full messages.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionMeta {
    pub id: String,
    pub timestamp: String,
    pub target: String,
    pub llm_profile: Option<String>,
    /// Preview of the first user message (or system message).
    pub preview: String,
}

impl From<&Session> for SessionMeta {
    fn from(s: &Session) -> Self {
        let preview = s
            .messages
            .iter()
            .find(|b| matches!(b, ChatBlock::User(_)))
            .or_else(|| s.messages.first())
            .map(|b| b.preview())
            .unwrap_or_default();
        Self {
            id: s.id.clone(),
            timestamp: s.timestamp.clone(),
            target: s.target.clone(),
            llm_profile: s.llm_profile.clone(),
            preview,
        }
    }
}

// ---------------------------------------------------------------------------
// Session methods
// ---------------------------------------------------------------------------

impl Session {
    /// Truncate `input_history` to at most [`MAX_INPUT_HISTORY`] entries,
    /// keeping the most recent.
    pub fn truncate_history(&mut self) {
        let max = MAX_INPUT_HISTORY;
        if self.input_history.len() > max {
            let excess = self.input_history.len() - max;
            self.input_history.drain(0..excess);
        }
    }
}

// ---------------------------------------------------------------------------
// SessionStore
// ---------------------------------------------------------------------------

/// Manages session files on disk.
pub struct SessionStore {
    dir: PathBuf,
}

impl SessionStore {
    /// Returns the sessions directory path.
    pub fn dir(&self) -> &std::path::Path {
        &self.dir
    }

    /// Create a store with a specific base directory.
    ///
    /// The sessions directory will be `base_dir/filar/sessions`.
    /// This allows external consumers (bots, mobile apps) to specify a
    /// platform-appropriate path without relying on `APPDATA` or `HOME`.
    pub fn new(base_dir: PathBuf) -> Result<Self> {
        let dir = base_dir.join("filar").join("sessions");
        std::fs::create_dir_all(&dir)?;
        Ok(Self { dir })
    }

    /// Create a store using the platform-default base directory.
    ///
    /// On Windows this is `%APPDATA%`; on Unix it is `$HOME`.
    /// For cross-compilation targets (Android, iOS) where these variables
    /// may not be set, use [`new`](Self::new) with an explicit path.
    pub fn with_default_dir() -> Result<Self> {
        Self::new(default_base_dir()?)
    }

    /// Save a session to disk (overwrites if the ID already exists).
    pub fn save(&self, session: &Session) -> Result<()> {
        let path = self.dir.join(format!("{}.json", session.id));
        let json = serde_json::to_string_pretty(session)
            .map_err(|e| CoreError::Other(format!("failed to serialise session: {e}")))?;
        std::fs::write(&path, json)?;
        tracing::info!(session_id = %session.id, path = %path.display(), "session saved");
        Ok(())
    }

    /// Load a session by ID. Returns `None` if the file does not exist.
    pub fn load(&self, id: &str) -> Result<Option<Session>> {
        let path = self.dir.join(format!("{id}.json"));
        if !path.exists() {
            return Ok(None);
        }
        let contents = std::fs::read_to_string(&path)?;
        let session: Session = serde_json::from_str(&contents)
            .map_err(|e| CoreError::Other(format!("failed to parse session {id}: {e}")))?;
        Ok(Some(session))
    }

    /// List metadata for all stored sessions, sorted newest-first.
    pub fn list(&self) -> Result<Vec<SessionMeta>> {
        let mut metas = Vec::new();
        if !self.dir.exists() {
            return Ok(metas);
        }
        for entry in std::fs::read_dir(&self.dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("json") {
                continue;
            }
            match std::fs::read_to_string(&path) {
                Ok(contents) => {
                    match serde_json::from_str::<Session>(&contents) {
                        Ok(session) => metas.push(SessionMeta::from(&session)),
                        Err(e) => {
                            tracing::warn!(path = %path.display(), error = %e, "skipping unparseable session file");
                        }
                    }
                }
                Err(e) => {
                    tracing::warn!(path = %path.display(), error = %e, "skipping unreadable session file");
                }
            }
        }
        // Sort newest-first (IDs are timestamps, so string sort works).
        metas.sort_by(|a, b| b.id.cmp(&a.id));
        Ok(metas)
    }

    /// Delete sessions beyond `max`, keeping the newest.
    pub fn prune_to(&self, max: usize) -> Result<()> {
        let metas = self.list()?;
        if metas.len() <= max {
            return Ok(());
        }
        // metas is sorted newest-first; delete everything after index `max`.
        for meta in metas.into_iter().skip(max) {
            let path = self.dir.join(format!("{}.json", meta.id));
            tracing::info!(session_id = %meta.id, "pruning old session");
            let _ = std::fs::remove_file(&path);
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Determine the platform-default base directory for filar data.
///
/// Returns `%APPDATA%` on Windows, `$HOME` on Unix.
/// The sessions directory is `base/filar/sessions`.
///
/// This function does **not** create any directories — use it when you only
/// need the base path (e.g. for `settings.json`, `pending_launch.json`).
/// For session storage, use [`SessionStore::with_default_dir`] instead.
pub fn default_base_dir() -> Result<PathBuf> {
    if cfg!(windows) {
        std::env::var("APPDATA")
            .map(PathBuf::from)
            .map_err(|_| CoreError::Other("APPDATA environment variable not set".into()))
    } else {
        std::env::var("HOME")
            .map(PathBuf::from)
            .map_err(|_| CoreError::Other("HOME environment variable not set".into()))
    }
}

/// Generate a session ID and human-readable timestamp from the current time.
pub fn now_session_id() -> (String, String) {
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();

    // Simple UTC timestamp formatting without external deps.
    let (year, month, day, hour, min, sec) = unix_to_ymdhms(secs);
    let id = format!("{secs}");
    let timestamp = format!("{year:04}-{month:02}-{day:02} {hour:02}:{min:02}:{sec:02}");
    (id, timestamp)
}

/// Convert a Unix timestamp (seconds) to broken-down UTC time.
///
/// This is a minimal implementation that avoids pulling in `chrono`.
fn unix_to_ymdhms(secs: u64) -> (u32, u32, u32, u32, u32, u32) {
    let days = (secs / 86_400) as i64;
    let rem = secs % 86_400;
    let hour = (rem / 3600) as u32;
    let min = ((rem % 3600) / 60) as u32;
    let sec = (rem % 60) as u32;

    // Days since 1970-01-01 → calendar date (Howard Hinnant's algorithm).
    let z = days + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = (z - era * 146_097) as u64;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe as i64 + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32;
    let m = if mp < 10 { mp + 3 } else { mp - 9 } as u32;
    let year = if m <= 2 { y + 1 } else { y } as u32;

    (year, m, d, hour, min, sec)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn session_meta_from_session() {
        let session = Session {
            id: "123".into(),
            timestamp: "2026-06-21 12:00:00".into(),
            target: "local".into(),
            llm_profile: Some("default".into()),
            messages: vec![
                ChatBlock::System("connected".into()),
                ChatBlock::User("find port 8080".into()),
                ChatBlock::Agent("running lsof".into()),
            ],
            input_history: vec![],
            tokens_in: 0,
            tokens_out: 0,
            cost_usd: None,
            per_profile: HashMap::new(),
            last_served_model: None,
        };
        let meta = SessionMeta::from(&session);
        assert_eq!(meta.id, "123");
        assert_eq!(meta.target, "local");
        assert_eq!(meta.preview, "You: find port 8080");
    }

    #[test]
    fn session_meta_empty_messages() {
        let session = Session {
            id: "1".into(),
            timestamp: "t".into(),
            target: "t".into(),
            llm_profile: Some("t".into()),
            messages: vec![],
            input_history: vec![],
            tokens_in: 0,
            tokens_out: 0,
            cost_usd: None,
            per_profile: HashMap::new(),
            last_served_model: None,
        };
        let meta = SessionMeta::from(&session);
        assert!(meta.preview.is_empty());
    }

    #[test]
    fn session_store_save_load_roundtrip() {
        // Use a temp directory for testing.
        let tmp = std::env::temp_dir().join(format!("filar_test_{}", std::process::id()));
        std::fs::create_dir_all(&tmp).unwrap();

        let store = SessionStore {
            dir: tmp.clone(),
        };

        let session = Session {
            id: "999".into(),
            timestamp: "2026-01-01 00:00:00".into(),
            target: "test".into(),
            llm_profile: Some("glm".into()),
            messages: vec![
                ChatBlock::User("hello".into()),
                ChatBlock::Agent("world".into()),
            ],
            input_history: vec!["ls -la".into(), "find port".into()],
            tokens_in: 0,
            tokens_out: 0,
            cost_usd: None,
            per_profile: HashMap::new(),
            last_served_model: None,
        };

        store.save(&session).unwrap();
        let loaded = store.load("999").unwrap().unwrap();
        assert_eq!(loaded.id, "999");
        assert_eq!(loaded.target, "test");
        assert_eq!(loaded.messages.len(), 2);
        assert_eq!(loaded.input_history, session.input_history);

        let metas = store.list().unwrap();
        assert_eq!(metas.len(), 1);
        assert_eq!(metas[0].preview, "You: hello");

        // Loading non-existent session.
        assert!(store.load("nonexistent").unwrap().is_none());

        // Clean up.
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn session_store_prune() {
        let tmp = std::env::temp_dir().join(format!("filar_prune_{}", std::process::id()));
        std::fs::create_dir_all(&tmp).unwrap();

        let store = SessionStore {
            dir: tmp.clone(),
        };

        // Save 5 sessions with different IDs (timestamps).
        for i in 1..=5u64 {
            let session = Session {
                id: format!("{i:010}"),
                timestamp: format!("t{i}"),
                target: "t".into(),
                llm_profile: Some("t".into()),
                messages: vec![ChatBlock::User(format!("msg{i}"))],
                input_history: vec![],
            tokens_in: 0,
            tokens_out: 0,
            cost_usd: None,
            per_profile: HashMap::new(),
            last_served_model: None,
            };
            store.save(&session).unwrap();
        }

        // Prune to 3.
        store.prune_to(3).unwrap();
        let metas = store.list().unwrap();
        assert_eq!(metas.len(), 3);
        // Newest 3 kept (IDs 0000000005, 0000000004, 0000000003).
        assert_eq!(metas[0].id, "0000000005");
        assert_eq!(metas[2].id, "0000000003");

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn session_store_new_creates_sessions_dir() {
        let tmp = std::env::temp_dir().join(format!(
            "filar_new_test_{}_{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos()
        ));
        // Ensure clean state.
        let _ = std::fs::remove_dir_all(&tmp);

        let store = SessionStore::new(tmp.clone()).unwrap();
        let expected = tmp.join("filar").join("sessions");
        assert!(expected.exists(), "sessions directory should be created");
        assert_eq!(store.dir(), expected);

        // Clean up.
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn session_store_with_default_dir_resolves_platform_path() {
        // with_default_dir() should succeed when APPDATA (Windows) or HOME (Unix)
        // is set, and the resulting directory should be base/filar/sessions.
        let store = SessionStore::with_default_dir();
        // In CI / test environments the env var is usually set.
        if let Ok(s) = store {
            assert!(
                s.dir().ends_with(std::path::Path::new("filar/sessions")),
                "dir should end with filar/sessions, got: {}",
                s.dir().display()
            );
            assert!(s.dir().exists(), "directory should exist after creation");
        }
        // If env var is not set, that's also acceptable in exotic environments.
    }

    #[test]
    fn default_base_dir_does_not_create_directories() {
        // default_base_dir() should return a path but NOT create any directories.
        // We can't easily verify "no directory created" in general, but we can
        // check that the function returns a path that makes sense.
        if let Ok(base) = default_base_dir() {
            // The base dir itself (APPDATA or HOME) should already exist.
            assert!(base.exists(), "base directory should already exist");
        }
    }

    #[test]
    fn unix_to_ymdhms_epoch() {
        let (y, m, d, h, mi, s) = unix_to_ymdhms(0);
        assert_eq!((y, m, d, h, mi, s), (1970, 1, 1, 0, 0, 0));
    }

    #[test]
    fn tokens_in_out_roundtrip() {
        let s = Session {
            id: "1".into(), timestamp: "t".into(), target: "t".into(),
            llm_profile: Some("glm".into()), messages: vec![], input_history: vec![],
            tokens_in: 150, tokens_out: 300,
            cost_usd: None, per_profile: HashMap::new(), last_served_model: None,
        };
        let json = serde_json::to_string(&s).unwrap();
        assert!(json.contains("tokens_in"), "must serialize tokens_in");
        assert!(json.contains("150"), "must serialize value");
        let loaded: Session = serde_json::from_str(&json).unwrap();
        assert_eq!(loaded.tokens_in, 150);
        assert_eq!(loaded.tokens_out, 300);
    }

    #[test]
    fn tokens_in_out_backward_compat() {
        let json = r#"{"id":"1","timestamp":"x","target":"x","llm_profile":"x","messages":[],"input_history":[]}"#;
        let loaded: Session = serde_json::from_str(json).unwrap();
        assert_eq!(loaded.tokens_in, 0, "missing field → default 0");
        assert_eq!(loaded.tokens_out, 0);
    }

    #[test]
    fn unix_to_ymdhms_known_date() {
        let (y, _m, _d, _h, _mi, _s) = unix_to_ymdhms(1_782_045_045);
        assert_eq!(y, 2026);
    }

    // ── input_history tests ────────────────────────────────────────────

    #[test]
    fn input_history_serialize_roundtrip() {
        let session = Session {
            id: "1".into(),
            timestamp: "t".into(),
            target: "t".into(),
            llm_profile: Some("t".into()),
            messages: vec![],
            input_history: vec!["ls".into(), "find port 8080".into()],
            tokens_in: 0,
            tokens_out: 0,
            cost_usd: None,
            per_profile: HashMap::new(),
            last_served_model: None,
        };
        let json = serde_json::to_string_pretty(&session).unwrap();
        assert!(json.contains("input_history"), "JSON must contain input_history");
        assert!(json.contains("find port 8080"), "must contain history entries");
        let loaded: Session = serde_json::from_str(&json).unwrap();
        assert_eq!(loaded.input_history.len(), 2);
        assert_eq!(loaded.input_history[0], "ls");
        assert_eq!(loaded.input_history[1], "find port 8080");
    }

    #[test]
    fn input_history_backward_compat_no_field() {
        // JSON from a session saved by the old version — no input_history field.
        let json = r#"{
            "id":"123",
            "timestamp":"2026-01-01 00:00:00",
            "target":"test",
            "llm_profile":"glm",
            "messages":[{"User":"hello"},{"Agent":"world"}]
        }"#;
        let session: Session = serde_json::from_str(json).unwrap();
        assert_eq!(session.id, "123");
        assert!(session.input_history.is_empty(), "missing field → default empty");
    }

    #[test]
    fn truncate_input_history_keeps_last_entries() {
        let mut session = Session {
            id: "1".into(),
            timestamp: "t".into(),
            target: "t".into(),
            llm_profile: Some("t".into()),
            messages: vec![],
            input_history: (0..250).map(|i| format!("entry{i}")).collect(),
            tokens_in: 0,
            tokens_out: 0,
            cost_usd: None,
            per_profile: HashMap::new(),
            last_served_model: None,
        };
        assert!(session.input_history.len() > MAX_INPUT_HISTORY);
        session.truncate_history();
        assert_eq!(session.input_history.len(), MAX_INPUT_HISTORY);
        assert_eq!(session.input_history[0], "entry50");
        assert_eq!(session.input_history.last().unwrap(), "entry249");
    }

    #[test]
    fn session_backward_compat_without_new_fields() {
        let old_json = r#"{
            "id":"1","timestamp":"t","target":"t",
            "messages":[],
            "input_history":[],
            "tokens_in":100,
            "tokens_out":200
        }"#;
        let s: Session = serde_json::from_str(old_json).unwrap();
        assert_eq!(s.tokens_in, 100);
        assert_eq!(s.tokens_out, 200);
        assert_eq!(s.cost_usd, None);
        assert!(s.per_profile.is_empty());
        assert_eq!(s.last_served_model, None);
    }
}
